name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Google Container Registry
        env:
          GCP_PROJECT: ${{ secrets.KEYGCLOUD }}
        run: |
          gcloud auth activate-service-account $GCP_PROJECT

      - name: Build the Docker image
        run: docker build -t europe-west9-docker.pkg.dev/pokedevops/student-arnaud/pokemon .

      - name: Push the Docker image
        run: docker push europe-west9-docker.pkg.dev/pokedevops/student-arnaud/pokemon

      - name: Deploy to Cloud Run
        run: gcloud run deploy --image=europe-west9-docker.pkg.dev/pokedevops/student-arnaud/pokemon service-student-arnaud-dev -- project pokedevops
