name: Build, Push & Deploy Docker Image to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.KEYGCLOUD }}"

      - name: Configure Docker for Google Cloud
        run: |
          gcloud auth configure-docker europe-west9-docker.pkg.dev

      - name: Get the tag
        id: get-tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker tag europe-west9-docker.pkg.dev/pokedevops/student-arnaud/pokemon:$GITHUB_SHA europe-west9-docker.pkg.dev/pokedevops/student-arnaud/pokemon:$TAG_NAME

      - name: Push the Docker image
        run: docker push europe-west9-docker.pkg.dev/pokedevops/student-arnaud/pokemon:$TAG_NAME

      - name: Deploy to Google Cloud Run
        run: gcloud run deploy service-student-arnaud-preprod --image=europe-west9-docker.pkg.dev/pokedevops/student-arnaud/pokemon:${GITHUB_SHA} --project pokedevops --region europe-west9 --allow-unauthenticated
